// Mocks generated by Mockito 5.4.2 from annotations
// in lennar_associates/test/login/domain/presentation/blocs/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:lennar_associates/login/domain/repositories/login_repository.dart'
    as _i3;
import 'package:lennar_associates/login/domain/usecases/login_submit.dart'
    as _i6;
import 'package:lennar_associates/shared/network/failures.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepository extends _i1.Mock implements _i3.LoginRepository {
  MockLoginRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, bool>> loginSubmit({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginSubmit,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ServerFailure, bool>>.value(
            _FakeEither_0<_i5.ServerFailure, bool>(
          this,
          Invocation.method(
            #loginSubmit,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, bool>>);
}

/// A class which mocks [PostLoginSubmit].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostLoginSubmit extends _i1.Mock implements _i6.PostLoginSubmit {
  MockPostLoginSubmit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ServerFailure, bool>> execute({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #username: username,
            #password: password,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.ServerFailure, bool>>.value(
            _FakeEither_0<_i5.ServerFailure, bool>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #username: username,
              #password: password,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ServerFailure, bool>>);
}
